#!/usr/bin/env node
/**
 * build.js — cross-platform production build for the Leap International site.
 *
 *   1. Build the admin panel (admin_src, Vite)        [skip with --skip-admin]
 *   2. Assemble dist/ (static site + admin at /admin + Pages Functions)
 *   3. Run the SEO/GEO build step (scripts/build-seo.js)
 *
 * Replaces the previous Unix-only shell pipeline so the build works
 * identically on Windows, Netlify and Vercel.
 *
 * Usage: node scripts/build.js [--skip-admin]
 */

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const DIST = path.join(ROOT, 'dist');
const SKIP_ADMIN = process.argv.includes('--skip-admin');

const NPM = process.platform === 'win32' ? 'npm.cmd' : 'npm';

const STATIC_ENTRIES = [
  'index.html', 'pages', 'images', 'content', 'js', 'functions', 'robots.txt',
  'FOI_logo.png', 'FOI_logo.svg', 'FOI_logo_192px.png', 'FOI_logo_384px.png',
  // sitemap.xml intentionally excluded — regenerated by build-seo.js
];

function run(cmd, args, cwd) {
  // Windows: .cmd/.bat shims (npm.cmd) require a shell since Node 20 (CVE-2024-27980),
  // but node.exe must NOT go through a shell or the space in "C:\Program Files" splits.
  const needsShell = process.platform === 'win32' && /\.(cmd|bat)$/i.test(cmd);
  const res = spawnSync(cmd, args, { cwd, stdio: 'inherit', shell: needsShell });
  if (res.status !== 0) {
    console.error(`Command failed: ${cmd} ${args.join(' ')} (cwd: ${cwd})`);
    process.exit(res.status || 1);
  }
}

function main() {
  // --- 1. admin panel -------------------------------------------------------
  const adminDist = path.join(ROOT, 'admin_src', 'dist');
  if (SKIP_ADMIN) {
    console.log('== Step 1/3: admin build skipped (--skip-admin)');
  } else {
    console.log('== Step 1/3: building admin panel');
    if (!fs.existsSync(path.join(ROOT, 'admin_src', 'node_modules'))) {
      run(NPM, ['install'], path.join(ROOT, 'admin_src'));
    }
    run(NPM, ['run', 'build'], path.join(ROOT, 'admin_src'));
  }

  // preserve an existing admin build when skipping the admin build
  const adminBackup = path.join(ROOT, '.admin_dist_backup');
  if (SKIP_ADMIN && fs.existsSync(path.join(DIST, 'admin'))) {
    fs.rmSync(adminBackup, { recursive: true, force: true });
    fs.renameSync(path.join(DIST, 'admin'), adminBackup);
  }

  // --- 2. assemble dist -----------------------------------------------------
  console.log('== Step 2/3: assembling dist/');
  fs.rmSync(DIST, { recursive: true, force: true });
  fs.mkdirSync(DIST, { recursive: true });
  for (const entry of STATIC_ENTRIES) {
    fs.cpSync(path.join(ROOT, entry), path.join(DIST, entry), { recursive: true });
  }

  if (fs.existsSync(adminDist)) {
    fs.renameSync(adminDist, path.join(DIST, 'admin'));
  } else if (fs.existsSync(adminBackup)) {
    fs.renameSync(adminBackup, path.join(DIST, 'admin'));
  } else {
    console.warn('WARN: no admin build found — /admin/ will 404. Run without --skip-admin.');
  }
  fs.rmSync(adminBackup, { recursive: true, force: true });

  // --- 3. SEO/GEO build step -------------------------------------------------
  console.log('== Step 3/3: SEO/GEO transforms');
  run(process.execPath, [path.join(ROOT, 'scripts', 'build-seo.js'), DIST], ROOT);

  console.log('\nBuild complete -> dist/');
}

main();
